"""
Shared pytest fixtures.

Tests run against an in-memory SQLite database, not Postgres — the schema
only uses portable column types (String/Integer/Float/Boolean/Date/
DateTime/Text), so SQLite is a faithful enough stand-in for fast,
dependency-free unit/API tests. (Alembic's autogenerated migration was
itself verified against real Postgres-compatible DDL — see
backend/README.md's testing section for how to also run the suite against
a real local Postgres if you want that extra confidence.)
"""

from __future__ import annotations

import pytest
from fastapi.testclient import TestClient
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.pool import StaticPool

from app.config import Settings
from app.database import Base, get_db
from app.deps import settings_dep
from app.main import app


@pytest.fixture()
def db_session():
    engine = create_engine(
        "sqlite:///:memory:",
        connect_args={"check_same_thread": False},
        poolclass=StaticPool,
    )
    Base.metadata.create_all(engine)
    TestingSessionLocal = sessionmaker(bind=engine, autoflush=False, autocommit=False)
    session = TestingSessionLocal()
    try:
        yield session
    finally:
        session.close()
        Base.metadata.drop_all(engine)


@pytest.fixture()
def test_settings() -> Settings:
    # youtube_api_key/apify_api_token left blank on purpose: API-level tests
    # must never make real network calls. Scraper *parsing* logic is tested
    # separately, offline, against recorded sample payloads.
    return Settings(
        database_url="sqlite:///:memory:",
        youtube_api_key="",
        apify_api_token="",
        scrape_trigger_api_key="test-secret",
        cors_origins="http://localhost:5173",
    )


@pytest.fixture()
def client(db_session, test_settings):
    def _get_db_override():
        yield db_session

    def _settings_dep_override():
        return test_settings

    app.dependency_overrides[get_db] = _get_db_override
    app.dependency_overrides[settings_dep] = _settings_dep_override
    with TestClient(app) as c:
        yield c
    app.dependency_overrides.clear()
