"""init

Revision ID: 0001
Revises: 
Create Date: 2026-09-03 10:13:29.460263
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('handle', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('avatar_initials', sa.String(length=4), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('subscriber_count', sa.Integer(), nullable=True),
    sa.Column('cohort', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channels_cohort'), 'channels', ['cohort'], unique=False)
    op.create_index('ix_channels_platform_external_id', 'channels', ['platform', 'external_id'], unique=True)
    op.create_table('scrape_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('channels_processed', sa.Integer(), nullable=False),
    sa.Column('videos_upserted', sa.Integer(), nullable=False),
    sa.Column('youtube_quota_units_used', sa.Integer(), nullable=False),
    sa.Column('apify_runs_started', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scrape_runs_started_at', 'scrape_runs', ['started_at'], unique=False)
    op.create_table('videos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('external_url', sa.String(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.Date(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('format', sa.String(length=8), nullable=False),
    sa.Column('avg_views_baseline', sa.Float(), nullable=True),
    sa.Column('overperform_ratio', sa.Float(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_videos_channel_published', 'videos', ['channel_id', 'published_at'], unique=False)
    op.create_index(op.f('ix_videos_overperform_ratio'), 'videos', ['overperform_ratio'], unique=False)
    op.create_index('ix_videos_platform_published', 'videos', ['platform', 'published_at'], unique=False)
    op.create_index(op.f('ix_videos_published_at'), 'videos', ['published_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_published_at'), table_name='videos')
    op.drop_index('ix_videos_platform_published', table_name='videos')
    op.drop_index(op.f('ix_videos_overperform_ratio'), table_name='videos')
    op.drop_index('ix_videos_channel_published', table_name='videos')
    op.drop_table('videos')
    op.drop_index('ix_scrape_runs_started_at', table_name='scrape_runs')
    op.drop_table('scrape_runs')
    op.drop_index('ix_channels_platform_external_id', table_name='channels')
    op.drop_index(op.f('ix_channels_cohort'), table_name='channels')
    op.drop_table('channels')
    # ### end Alembic commands ###
